name: foto_share
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core:
  flutter_bloc:
  equatable:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  cloud_firestore_web: ^2.6.10
  flutter_shimmer:
  image_picker:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  #<a href="https://www.flaticon.com/free-icons/instagram" title="instagram icons">Instagram icons created by Pixel perfect - Flaticon</a>

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/instagram.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/instagram.png
